
export enum CartActionType {

  ADD_CART = "ADD_CART",
  SET_CART_ITEMS = 'SET_CART_ITEMS',
  ADD_CART_ITEM = 'ADD_CART_ITEM',
  DELETE_CART_ITEM = 'DELETE_CART_ITEM',
  UPDATE_CART_ITEM = 'UPDATE_CART_ITEMS',
  DELETE_CART = 'DELETE_CART',
  RESET_CART = 'RESET_CART'

}

export enum AuthActionType {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  ADD_SOCIEL_USER = "ADD_SOCIEL_USER",
  ADD_ACCESS_TOKEN = "ADD_ACCESS_TOKEN",
  ADD_REFRESH_TOKEN = "ADD_REFRESH_TOKEN",

}
