
export enum CartActionType {

  ADD_CART = "ADD_CART",
  SET_CART_ITEMS = 'SET_CART_ITEMS',
  ADD_CART_ITEM = 'ADD_CART_ITEM',
  DELETE_CART_ITEM = 'DELETE_CART_ITEM',
  UPDATE_CART_ITEM = 'UPDATE_CART_ITEMS',
  DELETE_CART = 'DELETE_CART'

}
